services:
  planner:
    image: ghcr.io/zachkont/mealie-lunch-planner:latest
    container_name: mealie-lunch-planner
    restart: unless-stopped
    network_mode: host
    environment:
      - MEALIE_URL=${MEALIE_URL}
      - MEALIE_TOKEN=${MEALIE_TOKEN}
      - CRON_SCHEDULE=${CRON_SCHEDULE}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_ALLOWED_USER_ID=${TELEGRAM_ALLOWED_USER_ID}
      - TELEGRAM_NOTIFY_CHAT_IDS=${TELEGRAM_NOTIFY_CHAT_IDS}
